### ISSUE TITLE
mom and dad bot additions

### ISSUE THREAD

**Issue by isimovic** [heyqule/slackbot#1]
Mom Bot
Get off my case and go play that 007 game {username}!
I'm not a regular mom, I'm a cool, hip mom.
What does fleek mean {username}? Is it a fruit?

Dad Bot
Where's the converter {username}?
I'm learning how to hashtag. Hashtag conversation with Dank Inc.

**Comment by heyqule** [comment]
I'm learning how to hashtag. Hashtag conversation with Dank Inc. #{username}

lol... I changed this line a bit... Dad needs to hashtag someone when learning hashtag
